2021-11-28 19:32:57,900 (58818/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-11-28 19:32:57,901 (58818/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-11-28 19:32:57,908 (58818/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 594, in connect\n    raise e\n  File "/usr/local/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 581, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 260, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 306, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory\n\tIs the server running locally and accepting connections on that socket?\n\n'
2021-11-28 19:33:36,126 (59520/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-11-28 19:33:36,127 (59520/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-11-28 19:33:36,136 (59520/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 594, in connect\n    raise e\n  File "/usr/local/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 581, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 260, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 306, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory\n\tIs the server running locally and accepting connections on that socket?\n\n'
2021-11-28 19:37:05,417 (63234/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-11-28 19:37:05,418 (63234/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-11-28 19:37:10,794 (63234/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 581, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 260, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 306, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections?\nconnection to server at "localhost" (127.0.0.1), port 5432 failed: fe_sendauth: no password supplied\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 590, in connect\n    pgexecute = PGExecute(\n  File "/usr/local/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 260, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 306, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections?\nconnection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "zmwilliam"\n\n'
2021-11-28 19:37:21,761 (63546/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-11-28 19:37:21,762 (63546/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-11-28 19:37:49,687 (63546/MainThread) pgcli.pgexecute ERROR - sql: 'selec', error: SyntaxError('syntax error at or near "selec"\nLINE 1: selec\n        ^\n')
2021-11-28 19:37:49,688 (63546/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 472, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 507, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/local/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 168, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "selec"\nLINE 1: selec\n        ^\n\n'
2021-11-28 19:37:53,645 (63546/MainThread) pgcli.pgexecute ERROR - sql: 'select * from', error: SyntaxError('syntax error at end of input\nLINE 1: select * from\n                     ^\n')
2021-11-28 19:37:53,645 (63546/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 472, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 507, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/local/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 168, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at end of input\nLINE 1: select * from\n                     ^\n\n'
2021-11-28 19:38:06,622 (63546/MainThread) pgcli.pgexecute ERROR - sql: 'select * from event', error: UndefinedTable('relation "event" does not exist\nLINE 1: select * from event\n                      ^\n')
2021-11-28 19:38:06,622 (63546/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 472, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 507, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/local/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 168, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.UndefinedTable: relation "event" does not exist\nLINE 1: select * from event\n                      ^\n\n'
2021-11-28 19:38:11,817 (63546/MainThread) pgcli.pgexecute ERROR - sql: 'selec', error: SyntaxError('syntax error at or near "selec"\nLINE 1: selec\n        ^\n')
2021-11-28 19:38:11,817 (63546/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 472, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 507, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/local/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 168, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "selec"\nLINE 1: selec\n        ^\n\n'
2021-11-28 19:38:39,118 (64936/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-11-28 19:38:39,118 (64936/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-11-28 19:38:39,129 (64936/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 594, in connect\n    raise e\n  File "/usr/local/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 581, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 260, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 306, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/Cellar/pgcli/3.2.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory\n\tIs the server running locally and accepting connections on that socket?\n\n'
2021-11-28 19:38:48,731 (65136/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-11-28 19:38:48,732 (65136/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-11-28 19:45:07,866 (71920/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-11-28 19:45:07,866 (71920/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-11-28 19:45:22,014 (72217/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-11-28 19:45:22,015 (72217/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-11-28 19:45:50,895 (72747/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-11-28 19:45:50,895 (72747/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-11-28 19:45:55,170 (72837/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-11-28 19:45:55,171 (72837/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-11-28 19:46:37,716 (73643/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-11-28 19:46:37,717 (73643/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-11-28 19:56:26,372 (86241/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-11-28 19:56:26,373 (86241/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
